package: mform
version: '8.0.0-beta2'
name: MForm
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mform
page:
    title: 'translate:title'
    pjax: true
    perm: admin[]
    icon: rex-icon fa-diagram-next
    subpages:
        docs:
            title: 'translate:help'
            icon: rex-icon fa-info-circle
            perm: mform[docs]
            hidden: true
        demo:
            title: 'translate:demo'
            icon: rex-icon fa-desktop
            perm: mform[demo]

requires:
    php: '>=7.4'
    redaxo: '^5.10.0'

conflicts:
    packages:
        ui_tools: '<1.0.0'
