package: mform
version: '6.0.13'
name: MForm
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mform
page:
    title: 'translate:title'
    pjax: true
    perm: admin[]
    icon: rex-icon fa-subway
    subpages:
        overview: { title: 'translate:overview' }
        demo:
            title: 'translate:referenz_demo'
            subpages:
                pjax: true
                demo_base: { title: 'translate:demo_base' }
                demo_extended: { title: 'translate:demo_extended' }
                demo_expert: { title: 'translate:demo_expert' }
                # demo_community: { title: 'translate:demo_community' }
default_config:
    mform_theme: 'default_theme'

requires:
    php: '>=7.3'
    redaxo: '^5.10.0'

system_plugins:
    - docs
conflicts:
    packages:
        ui_tools: '<1.0.0'
