package: mform
version: '8.1.4'
name: MForm
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mform
page:
    title: 'translate:title'
    pjax: true
    perm: admin[]
    icon: rex-icon fa-diagram-next
    subpages:
        demo:
            title: 'translate:reference_demo'
            subpages:
                demo_base: { title: 'translate:demo_base' }
                demo_wrapper: { title: 'translate:demo_wrapper' }
                demo_extended: { title: 'translate:demo_extended' }
                demo_repeater: { title: 'translate:demo_repeater' }
                demo_expert: { title: 'translate:demo_expert' }
        docs:
            title: 'translate:help'
            icon: rex-icon fa-info-circle
            perm: mform[docs]
            hidden: true
        changelog:
            title: 'translate:changelog'
            subPath: CHANGELOG.md
            itemClass: pull-right

requires:
    php: '>7.4'
    redaxo: '^5.17.0'

conflicts:
    packages:
        ui_tools: '<1.0.0'
