package: mform
version: '8.0.0-beta2'
name: MForm
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mform
page:
    title: 'translate:title'
    pjax: true
    perm: admin[]
    icon: rex-icon fa-solid fa-diagram-next
    subpages:
        mform_demo:
            title: 'translate:mform_reference_demo'
            subpages:
                pjax: true
                demo_base: { title: 'translate:demo_base' }
                demo_wrapper: { title: 'translate:demo_wrapper' }
                demo_extended: { title: 'translate:demo_extended' }
                demo_expert: { title: 'translate:demo_expert' }
        changelog:
            title: 'translate:changelog'
            subPath: CHANGELOG.md
            itemclass: pull-right
        help:
            title: 'translate:help'
            subPath: README.md
            itemclass: pull-right

requires:
    php: '>=7.4'
    redaxo: '^5.17.0'

conflicts:
    packages:
        ui_tools: '<1.0.0'
